#' Write output files based on file extensions.
#' @param object any object that can be coerced to a data.frame with 
#' as.data.frame() methods. Can also be a list of objects with the same 
#' requirements. In the latter case, the file name will be parsed into a prefix
#' and file extension, and the name of the object will be inserted between them
#' when writen to either a csv or tsv file.
#' @param file character File name with extension. Supported formats include:
#' csv, tsv, rds, and RData.
#' @author Christopher Nobles, Ph.D.

writeOutputFile <- function(object, file, format = "any"){
  if(format == "any"){
    fileType <- stringr::str_extract(file, "[\\w]+$")
  }else{
    fileType <- format
  }
  objectClass <- class(object)
  if(fileType == "csv" & objectClass != "list"){
    write.csv(
      as.data.frame(object, row.names = NULL), 
      file = file, 
      quote = FALSE, 
      row.names = FALSE)
  }else if(fileType == "tsv" & objectClass != "list"){
    write.table(
      as.data.frame(object, row.names = NULL), 
      file = file, 
      sep = "\t",
      quote = FALSE, 
      row.names = FALSE)
  }else if(fileType == "csv" & objectClass == "list"){
    prefix <- gsub("csv$", "", file)
    if(is.null(names(object))) names(object) <- 1:length(object)
    objectNames <- names(object)
    fileNames <- paste0(prefix, objectNames, ".csv")
    null <- mapply(function(ob, fileName){
        ob <- as.data.frame(ob, row.names = NULL)
        write.csv(ob, fileName, quote = FALSE, row.names = FALSE)
      }, ob = object, fileName = fileNames)
  }else if(fileType == "tsv" & objectClass == "list"){
    prefix <- gsub("tsv$", "", file)
    objectNames <- names(object)
    fileNames <- paste0(prefix, objectNames, ".tsv")
    null <- mapply(function(ob, fileName){
        ob <- as.data.frame(ob, row.names = NULL)
        write.table(ob, fileName, sep = "\t", quote = FALSE, row.names = FALSE)
      }, ob = object, fileName = fileNames)
  }else if(fileType == "rds"){
    saveRDS(object, file)
  }else if(fileType == "RData"){
    save(object, file)
  }else{
    stop("Unsupported file type. Supported: csv, tsv, rds, and RData.")
  }
}

#' Write empty files for requested files when coupling returns 0 alignments.
#' @description Several steps can during the coupling process may return 0 
#' results. When this happens, this function will write out empty files for 
#' those requested at the commandline. For this, the function takes 'args' as
#' its first and only argument.
#' @param args arguments generated by the commandline and argparse.
#' @author Christopher Nobles, Ph.D.

write_null_output <- function(args){
  if(!exists("uniq_sites")){
    metaCols <- read.table(
      text = "", 
      col.names = c("lociPairKey", "readPairKey", "sampleName", "ID"),
      colClasses = c("character", "character", "character", "character"))
    g <- GRanges()
    mcols(g) <- metaCols
    writeOutputFile(object = g, file = args$uniqOutput)}
  if(!exists("cond_sites") & !is.null(args$condSites)){
    writeOutputFile(object = GRanges(), file = args$condSites)}
  if(!exists("chimeraData") & !is.null(args$chimeras)){
    writeOutputFile(
      object = list("read_info" = data.frame(), "alignments" = GRangesList()), 
      file = args$chimeras,
      format = "rds")}
  if(!exists("multihitData") & !is.null(args$multihits)){
    writeOutputFile(
      object = list("unclustered_multihits" = GRanges(), 
                    "clustered_multihit_positions" = GRangesList(), 
                    "clustered_multihit_lengths" = list()),
      file = args$multihits,
      format = "rds")
  }
  if(args$stat != FALSE){
    if(exists("stat")){
      write.table(
        stat, file = args$stat,
        sep = ",", row.names = FALSE, col.names = FALSE, quote = FALSE)
    }else{
      write.table(
        data.frame(), file = args$stat,
        sep = ",", row.names = FALSE, col.names = FALSE, quote = FALSE)
    }
  }
}
